name: Deploy Backend Cloud Function

on:
  repository_dispatch:
    types: [deploy-backend]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        repository: your-username/test
        token: ${{ secrets.PRIVATE_REPO_PAT }}
        ref: ${{ github.event.client_payload.ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: datamanagement-coip
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy Accuracy Cloud Function
      run: |
        gcloud functions deploy accuracy_scoring \
          --region=us-central1 \
          --runtime=python310 \
          --trigger-http \
          --allow-unauthenticated \
          --entry-point=accuracy_scoring \
          --source=Backend/Accuracy \
          --service-account=datamanagement-coip@appspot.gserviceaccount.com
